name: 4ebur.net api

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run wireguard_example.py
      run: |
        python wireguard_example.py

    - name: Run socks5_example.py
      run: |
        python socks5_example.py

    - uses: actions/upload-artifact@v3
      with:
        name: output
        path: ./output
